services:
    db:
        container_name: db.${APP_NAMESPACE}
        image: postgres:17
        environment:
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            PGDATA: '/var/lib/postgresql/data/pgdata'
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports:
            - '${DB_PORT}:5432'
        networks:
            - app
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 4G
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: php.${APP_NAMESPACE}
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        depends_on:
            redis:
                condition: service_healthy
            db:
                condition: service_healthy
        networks:
            - app
    redis:
        restart: unless-stopped
        container_name: redis.${APP_NAMESPACE}
        image: redis:7.4.0
        volumes:
            - redis_data:/data
        ports:
            - '${REDIS_PORT:-}:6379'
        networks:
            - app
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 1s
            timeout: 3s
            retries: 30
        expose:
          - 6379
    prometheus:
      image: prom/prometheus
      container_name: prometheus.${APP_NAMESPACE}
      ports:
        - "9090:9090"
      volumes:
        - .docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      networks:
        - app

    grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - "3000:3000"
      volumes:
        - grafana_data:/var/lib/grafana
      networks:
        - app

    loki:
      image: grafana/loki:latest
      container_name: loki.${APP_NAMESPACE}
      ports:
        - "3100:3100"
      volumes:
        - .docker/grafana/loki-config.yml:/etc/loki/local-config.yaml
      networks:
        - app
    promtail:
      image: grafana/promtail:latest
      container_name: promtail.${APP_NAMESPACE}
      volumes:
        - ./:/var/log
        - .docker/grafana/promtail-config.yml:/etc/promtail/config.yml
      networks:
        - app
      command: -config.file=/etc/promtail/config.yml
    node-exporter:
      image: prom/node-exporter
      container_name: node-exporter.${APP_NAMESPACE}
      ports:
        - "9100:9100"
      networks:
        - app
volumes:
    pg_data:
    redis_data:
    loki_data:
    prometheus_data:
    promtail_data:
    grafana_data:
networks:
    app:
        driver: bridge
